### ISSUE TITLE
Error when running app in docker virtual container

### ISSUE THREAD

**Issue by njeans** [microsoft/ccf-app-samples#89] opened 2022-12-08 20:02 UTC
**Describe the bug**
I get an error of `terminating with uncaught exception of type std::logic_error: SGX enclaves are not supported in current build - cannot launch /usr/lib/ccf/libjs_generic.virtual.so` when trying to run an example with the docker virtual image

**Steps to reproduce**
I had to update the docker file to generate the member cert in the docker image since I can't install ccf locally but I don't think that would cause such an error. 

1.  update banking-app/docker/ccf_app_js.virtual to generate member0 cert in docker file
```
diff --git a/banking-app/docker/ccf_app_js.virtual b/banking-app/docker/ccf_app_js.virtual
index 2b9d6e6..a115605 100644
--- a/banking-app/docker/ccf_app_js.virtual
+++ b/banking-app/docker/ccf_app_js.virtual
@@ -10,11 +10,12 @@ COPY --from=builder /opt/ccf_virtual/lib/libjs_generic.virtual.so /usr/lib/ccf
 # copy configuration into image
 COPY ./constitution/*.js /app/
 COPY ./config/cchost_config_virtual_js.json /app/
-COPY ./workspace/docker_certificates/member0_cert.pem /app/
-COPY ./workspace/docker_certificates/member0_enc_pubk.pem /app/
 
 WORKDIR /app/
 
+COPY --from=builder /opt/ccf_virtual/bin/keygenerator.sh /app/
+RUN /app/keygenerator.sh --name member0 --gen-enc-key
+
 EXPOSE 8080/tcp
 
 CMD ["/usr/bin/cchost", "--config", "/app/cchost_config_virtual_js.json"]
```

2.  remove certificate generation from build_image.sh 
```
diff --git a/build_image.sh b/build_image.sh
index 9d9b9c9..51c7ca4 100755
--- a/build_image.sh
+++ b/build_image.sh
@@ -24,9 +24,9 @@ mkdir -p $app_path/workspace/docker_certificates
 
 echo "-- generating member0 certificates"
 # This is directly related to the member described in host config file 
-cd $app_path/workspace/docker_certificates
-$ccf_prefix/keygenerator.sh --name member0 --gen-enc-key
+#cd $app_path/workspace/docker_certificates
+#$ccf_prefix/keygenerator.sh --name member0 --gen-enc-key
```

3.  cd banking-app
4.  npm install
5.  make build-virtual
6. docker run banking-app:virtual

```
2022-12-08T19:48:25.962404Z        100 [info ] ../src/host/main.cpp:125             | CCF version: ccf-3.0.1
2022-12-08T19:48:25.962602Z        100 [info ] ../src/host/main.cpp:133             | Configuration file /app/cchost_config_virtual_js.json:
{
  "enclave": {
    "file": "/usr/lib/ccf/libjs_generic.virtual.so",
    "type": "Virtual"
  },
  "network": {
    "node_to_node_interface": {
      "bind_address": "172.17.0.3:8081"
    },
    "rpc_interfaces": {
      "main_interface": {
        "bind_address": "172.17.0.3:8080"
      }
    }
  },
  "command": {
    "type": "Start",
    "service_certificate_file": "/app/service_cert.pem",
    "start": {
      "constitution_files": [
        "/app/validate.js",
        "/app/apply.js",
        "/app/resolve.js",
        "/app/actions.js"
      ],
      "members": [
        {
          "certificate_file": "/app/member0_cert.pem",
          "encryption_public_key_file": "/app/member0_enc_pubk.pem"
        }
      ]
    }
  }
}
2022-12-08T19:48:25.962649Z        100 [info ] ../src/host/main.cpp:164             | Recovery threshold unset. Defaulting to number of initial consortium members with a public encryption key (1).
terminating with uncaught exception of type std::logic_error: SGX enclaves are not supported in current build - cannot launch /usr/lib/ccf/libjs_generic.virtual.so```

**Comment by takuro-sato** [comment] 2022-12-12 11:16
Thank you @njeans for raising this.
Confirmed that I could reproduce it. I'll investigate the reason.

**Comment by takuro-sato** [comment] 2022-12-12 17:36
Fixed by https://github.com/microsoft/ccf-app-samples/pull/94

@njeans
> since I can't install ccf locally

You may already know, but we recommend to use [Dev Container](https://code.visualstudio.com/docs/devcontainers/create-dev-container) by clicking "Open in VSCode" button in README.md since it's the easiest way to try this repository.

Please feel free to reopen this if you still have problem.

**Closed by takuro-sato** 2022-12-12 17:36 UTC
Labels: bug

**Comment by achamayou** [comment] 2022-12-13 14:26
@njeans your config is missing a platform:

```
  "enclave": {
    "file": "/usr/lib/ccf/libjs_generic.virtual.so",
    "platform": "Virtual"
    "type": "Virtual"
  },
```

**Comment by njeans** [comment] 2022-12-13 16:10
> @njeans your config is missing a platform:
> 
> ```
>   "enclave": {
>     "file": "/usr/lib/ccf/libjs_generic.virtual.so",
>     "platform": "Virtual"
>     "type": "Virtual"
>   },
> ```

Thank you! this worked
